random = math.random
math.randomseed(os.time())
emotes = {[":marecon:"]=true,
[":comfy:"]=true,
[":smileybeam:"]=true,
[":nawni:"]=true,
[":mascots:"]=true,
[":mareconthread:"]=true,
[":comfget:"]=true,
[":smileyget:"]=true,
[":nawnget:"]=true,
[":retroget:"]=true,
[":comfystops:"]=true,
[":hi:"]=true,
[":nawnio:"]=true,
[":sucks:"]=true,
[":pretty:"]=true,
[":ooo:"]=true,
[":ilovemarecon:"]=true,
[":lul:"]=true,
[":pickleget:"]=true,
[":sunbeam:"]=true,
[":berrybased:"]=true,
[":strem:"]=true,
[":kekbeam:"]=true,
[":boop:"]=true,
[":boopfast:"]=true,
[":boopfaster:"]=true,
[":boopwaytoofast:"]=true,
[":intenseboop:"]=true,
[":maximumoverboop:"]=true,
[":yay:"]=true,
[":wut:"]=true,
[":wub:"]=true,
[":woonadance:"]=true,
[":wiki:"]=true,
[":wiggle2:"]=true,
[":windy:"]=true,
[":wink:"]=true,
[":why:"]=true,
[":why2:"]=true,
[":wiggle:"]=true,
[":wakemeup:"]=true,
[":whip:"]=true,
[":twidance2:"]=true,
[":twiggypiggy:"]=true,
[":twidance:"]=true,
[":unf:"]=true,
[":twily:"]=true,
[":trixsweat:"]=true,
[":trixiebag:"]=true,
[":trixiecite:"]=true,
[":troll:"]=true,
[":twicrazy:"]=true,
[":teacher:"]=true,
[":tism:"]=true,
[":toss:"]=true,
[":thrust:"]=true,
[":sweetiebounce:"]=true,
[":sweat2:"]=true,
[":sweep:"]=true,
[":tavi:"]=true,
[":swibbles:"]=true,
[":sweat:"]=true,
[":sunbooty:"]=true,
[":sun:"]=true,
[":snoot:"]=true,
[":spoon:"]=true,
[":stomp:"]=true,
[":spray:"]=true,
[":squee:"]=true,
[":spook:"]=true,
[":spookdance:"]=true,
[":socksual:"]=true,
[":speeddance:"]=true,
[":smartpurple:"]=true,
[":smug:"]=true,
[":sniff:"]=true,
[":smugilee:"]=true,
[":smugpeetzer:"]=true,
[":smalljack:"]=true,
[":slurp:"]=true,
[":sillyfilly:"]=true,
[":sip:"]=true,
[":shootingstars:"]=true,
[":shock:"]=true,
[":silly:"]=true,
[":shrug:"]=true,
[":shiggy:"]=true,
[":scrunch3:"]=true,
[":shid:"]=true,
[":scrunch2:"]=true,
[":shakes:"]=true,
[":shake:"]=true,
[":scoot:"]=true,
[":scrunch:"]=true,
[":screm:"]=true,
[":scritch:"]=true,
[":sad:"]=true,
[":sadtwi:"]=true,
[":rose:"]=true,
[":scared:"]=true,
[":scaredchickun:"]=true,
[":rariwiggle:"]=true,
[":rock:"]=true,
[":rekt:"]=true,
[":riff:"]=true,
[":razzledazzle:"]=true,
[":rarasmug:"]=true,
[":rarijam:"]=true,
[":rarinom:"]=true,
[":rapgod:"]=true,
[":rarara:"]=true,
[":purp:"]=true,
[":rape:"]=true,
[":racistbarn:"]=true,
[":purpledance:"]=true,
[":quiet:"]=true,
[":pony:"]=true,
[":pressure:"]=true,
[":promise:"]=true,
[":professional:"]=true,
[":partygirl:"]=true,
[":ponka:"]=true,
[":peeved:"]=true,
[":ponk:"]=true,
[":partysoft:"]=true,
[":partyhard:"]=true,
[":peetzer:"]=true,
[":notimpressed:"]=true,
[":notcanon:"]=true,
[":ooober:"]=true,
[":nom:"]=true,
[":moonbooty:"]=true,
[":meh:"]=true,
[":moondance:"]=true,
[":neet:"]=true,
[":maresspin:"]=true,
[":maresfaster:"]=true,
[":maresfast:"]=true,
[":march:"]=true,
[":marble:"]=true,
[":mare:"]=true,
[":mares:"]=true,
[":loira:"]=true,
[":laughingmares:"]=true,
[":lulra:"]=true,
[":lewd:"]=true,
[":limey:"]=true,
[":kickyhooves:"]=true,
[":kek2:"]=true,
[":larson:"]=true,
[":kek:"]=true,
[":kek3:"]=true,
[":incest:"]=true,
[":juicebox:"]=true,
[":jew:"]=true,
[":hug:"]=true,
[":horse:"]=true,
[":hitwi:"]=true,
[":horn:"]=true,
[":hoofykicks:"]=true,
[":honesty:"]=true,
[":hoof:"]=true,
[":grounded:"]=true,
[":hen:"]=true,
[":glutes:"]=true,
[":gottagofast:"]=true,
[":glim:"]=true,
[":gasp:"]=true,
[":giddyup:"]=true,
[":giwtwm:"]=true,
[":gallop:"]=true,
[":forever:"]=true,
[":fun2:"]=true,
[":fusroyay:"]=true,
[":france:"]=true,
[":fun:"]=true,
[":flutterdance:"]=true,
[":fluttertree:"]=true,
[":flutternom:"]=true,
[":floss:"]=true,
[":flutterbitch:"]=true,
[":fillybop:"]=true,
[":firebutt:"]=true,
[":feels:"]=true,
[":fetish:"]=true,
[":eyebrow:"]=true,
[":faggot:"]=true,
[":fabulous:"]=true,
[":faust:"]=true,
[":excited:"]=true,
[":excite:"]=true,
[":egghead:"]=true,
[":eat:"]=true,
[":engineer:"]=true,
[":equestria:"]=true,
[":donkdance:"]=true,
[":dt:"]=true,
[":donk:"]=true,
[":doot:"]=true,
[":doubled:"]=true,
[":dog:"]=true,
[":diggingforgold:"]=true,
[":derpflip:"]=true,
[":diamond:"]=true,
[":derpdance:"]=true,
[":dashiewashie:"]=true,
[":darling:"]=true,
[":derp:"]=true,
[":datplot:"]=true,
[":ded:"]=true,
[":dangerzone:"]=true,
[":dansen:"]=true,
[":dance11:"]=true,
[":dance10:"]=true,
[":dance9:"]=true,
[":dance4:"]=true,
[":dance5:"]=true,
[":dance7:"]=true,
[":dance6:"]=true,
[":dance8:"]=true,
[":crusty:"]=true,
[":dance3:"]=true,
[":dance2:"]=true,
[":dance:"]=true,
[":creatura:"]=true,
[":communism:"]=true,
[":coof:"]=true,
[":cozy:"]=true,
[":clop:"]=true,
[":comfytwi:"]=true,
[":clap:"]=true,
[":carrotnom:"]=true,
[":clop2:"]=true,
[":cans.wav:"]=true,
[":cheer:"]=true,
[":cane:"]=true,
[":coco:"]=true,
[":chicken:"]=true,
[":cider:"]=true,
[":cake:"]=true,
[":brush:"]=true,
[":bug:"]=true,
[":burra:"]=true,
[":/):"]=true,
[":bueno:"]=true,
[":bread:"]=true,
[":boner:"]=true,
[":brap:"]=true,
[":bon3:"]=true,
[":booty:"]=true,
[":bon2:"]=true,
[":blue:"]=true,
[":bloom:"]=true,
[":bluefast:"]=true,
[":blini:"]=true,
[":bon:"]=true,
[":birthday:"]=true,
[":berryspooky:"]=true,
[":beegloira:"]=true,
[":berrycute:"]=true,
[":belle:"]=true,
[":beep:"]=true,
[":belli:"]=true,
[":banjo:"]=true,
[":barrelroll:"]=true,
[":bee:"]=true,
[":balloons:"]=true,
[":based:"]=true,
[":babs:"]=true,
[":applehop:"]=true,
[":appuldance:"]=true,
[":ajscrunch:"]=true,
[":ajbang:"]=true,
[":420:"]=true,
[":zigger:"]=true,
[":yellowquiet:"]=true,
[":2lewd:"]=true,
[":dashierock:"]=true,
[":amogus:"]=true,
[":happi:"]=true,
[":linky:"]=true,
[":derp.wave:"]=true,
[":dashplot:"]=true,
[":muffin.time:"]=true,
[":curious:"]=true,
[":good.show:"]=true,
[":what:"]=true,
[":ploota:"]=true,
[":3:"]=true,
[":tired:"]=true,
[":l:"]=true,
[":honk:"]=true,
[":ciderdance:"]=true,
[":drdplot:"]=true,
[":niggermare:"]=true,
[":marenigger:"]=true,
[":marenigga:"]=true,
[":moonbeam:"]=true,
[":faghug:"]=true,
[":reee:"]=true,
[":berrywink:"]=true,
[":tegmun:"]=true,
[":books:"]=true,
[":sisi:"]=true,
[":sleepy:"]=true,
[":thursday:"]=true,
[":roseclone:"]=true,
[":tolly:"]=true,
[":stretch:"]=true,
[":pinkwink:"]=true,
[":drip:"]=true,
[":numget:"]=true,
[":numgethd:"]=true,
[":ponktoy:"]=true,
[":pinkie.works:"]=true,
[":ponkwut:"]=true,
[":swatch:"]=true,
[":iwtcird:"]=true,
[":applause:"]=true,
[":grumpbon:"]=true,
[":faejam:"]=true,
[":twiggle:"]=true,
[":heh:"]=true,
[":salute:"]=true,
[":ote:"]=true,
[":gun:"]=true,
[":borked:"]=true,
[":brick:"]=true,
[":sunbale:"]=true,
[":hi5:"]=true,
[":huh:"]=true,
[":ponkster:"]=true,
[":anonjam:"]=true,
[":blender:"]=true,
[":gimp:"]=true,
[":brain:"]=true,
[":me:"]=true,
[":shh:"]=true,
[":shhh:"]=true,
[":when:"]=true,
[":seethe:"]=true,
[":awooga:"]=true,
[":appleshrug:"]=true,
[":amre:"]=true,
[":wine:"]=true,
[":sicko:"]=true,
[":sadponk:"]=true,
[":hi4:"]=true,
[":headbang:"]=true,
[":ambulance:"]=true,
[":sleep:"]=true,
[":angy:"]=true,
[":ponky:"]=true,
[":igotyourip:"]=true,
[":pwiggle:"]=true,
[":ruf:"]=true,
[":twhy:"]=true,
[":twidance1:"]=true,
[":delet:"]=true,
[":marewave:"]=true,
[":blahblah:"]=true,
[":welcome:"]=true,
[":swears:"]=true,
[":derpbop:"]=true,
[":huh.2:"]=true,
[":twihuh:"]=true,
[":fillyposting:"]=true,
[":pwiggle2:"]=true,
[":maud:"]=true,
[":numgetdance:"]=true,
[":yaybeam:"]=true,
[":suneyes:"]=true,
[":poomp:"]=true,
[":numswet:"]=true,
[":burmger:"]=true,
[":carlos:"]=true,
[":snowbeam:"]=true,
[":psst:"]=true,
[":movietime:"]=true,
[":matineedance:"]=true,
[":soireedance:"]=true,
[":gander:"]=true,
[":waitwhat:"]=true,
[":susget:"]=true,
[":bonstroke:"]=true,
[":wow:"]=true,
[":yowza:"]=true,
[":noice:"]=true,
[":numparty:"]=true,
[":pray:"]=true,
[":orbs:"]=true,
[":numorbs:"]=true,
[":superhyperpwiggle:"]=true,
[":westget:"]=true,
[":berryshock:"]=true,
[":oootwi:"]=true,
[":noiver:"]=true,
[":grump:"]=true,
[":hoofgasp:"]=true,
[":popcorn:"]=true,
[":ant:"]=true,
[":godforbid:"]=true,
[":popcorn2:"]=true,
[":mauddance:"]=true,
[":limeydance:"]=true,
[":really:"]=true,
[":numgetbeam:"]=true,
[":cheerget:"]=true,
[":hi3:"]=true,
[":butget:"]=true,
[":bewilderment:"]=true,
[":rumpa:"]=true,
[":loud2:"]=true,
[":kiss:"]=true,
[":numderdasea:"]=true,
[":rapget:"]=true,
[":frenchget:"]=true,
[":hmmget:"]=true,
[":numblink:"]=true,
[":fishbowlget:"]=true,
[":saiyanget:"]=true,
[":sadget:"]=true,
[":flyget:"]=true,
[":boopget:"]=true,
[":trixget:"]=true,
[":streamerget:"]=true,
[":lostget:"]=true,
[":wortget:"]=true,
[":gruntget:"]=true,
[":numyay:"]=true,
[":skibidi:"]=true,
[":wheeze:"]=true,
[":furget:"]=true,
[":lemon:"]=true,
[":lemonantget:"]=true,
[":blindget:"]=true,
[":lewdget:"]=true,
[":teeth:"]=true,
[":numver:"]=true,
[":donkbeam:"]=true,
[":mirrorget:"]=true,
[":numant:"]=true,
[":bwoomp:"]=true,
[":antget:"]=true,
[":haloget:"]=true,
[":dwarfget:"]=true,
[":fillyhug:"]=true,
[":fillyham:"]=true,
[":sirsget:"]=true,
[":starebeam:"]=true,
[":numblep:"]=true,
[":iwtcil:"]=true,
[":ponkflowersniff:"]=true,
[":belli2:"]=true,
[":exciteget:"]=true,
[":ilovethem:"]=true,
[":linkystand:"]=true,
[":sleepylinky:"]=true,
[":linkydance:"]=true,
[":berrydance:"]=true,
[":berryyay:"]=true,
[":hi2:"]=true,
[":lyrant:"]=true,
[":boomstick:"]=true,
[":loud:"]=true,
[":strawbeam:"]=true,
[":strawberrysmug:"]=true,
[":aikino:"]=true,
[":aislop:"]=true,
[":smileyspin:"]=true,
[":smileyspinfast:"]=true,
[":smileyspinfaster:"]=true,
[":X:"]=true,
[":pog:"]=true,
[":plootalive:"]=true,
[":smiley:"]=true,
[":just:"]=true,
[":glyraphid:"]=true,
[":eee:"]=true,
[":crocs:"]=true,
[":aerobics:"]=true,
[":faint:"]=true,
[":twinklehop:"]=true,
[":dapperget:"]=true,
[":glowget:"]=true,
[":machoget:"]=true,
[":numschwitz:"]=true,
[":pezget:"]=true,
[":slowget:"]=true,
[":strawget:"]=true,
[":tallget:"]=true,
[":washget:"]=true,
[":washgetfast:"]=true,
[":gangetbloo:"]=true,
[":gangetcrip:"]=true,
[":ganget:"]=true,
[":kot:"]=true,
[":wideget:"]=true,
[":numrect:"]=true,
[":pon3.stream:"]=true,
[":poledance:"]=true,
[":nawni.og:"]=true
}
emotesAssets = {
{ name = "marecon", url = "https://smart.bluefast.horse/catbox-6t5mq6.png"},
{ name = "comfy", url = "https://smart.bluefast.horse/catbox-he8yay.png"},
{ name = "smileybeam", url = "https://smart.bluefast.horse/catbox-nzzpk4.gif"},
{ name = "nawni", url = "https://smart.bluefast.horse/catbox-mh3w4o.png"},
{ name = "mascots", url = "https://smart.bluefast.horse/catbox-ojcahq.png"},
{ name = "mareconthread", url = "https://smart.bluefast.horse/pomf2-k3ooi0zs.png"},
{ name = "comfget", url = "https://smart.bluefast.horse/catbox-dgcd5e.png"},
{ name = "smileyget", url = "https://smart.bluefast.horse/catbox-x0paop.png"},
{ name = "nawnget", url = "https://smart.bluefast.horse/catbox-cn3x8v.png"},
{ name = "retroget", url = "https://smart.bluefast.horse/catbox-xftnh8.png"},
{ name = "comfystops", url = "https://smart.bluefast.horse/catbox-i77a1c.png"},
{ name = "hi", url = "https://smart.bluefast.horse/catbox-q2afhx.gif"},
{ name = "nawnio", url = "https://smart.bluefast.horse/catbox-y3ile7.png"},
{ name = "sucks", url = "https://smart.bluefast.horse/catbox-wajo8g.png"},
{ name = "pretty", url = "https://smart.bluefast.horse/smutty-miivxluhbma.png"},
{ name = "ooo", url = "https://smart.bluefast.horse/catbox-ucluzb.png"},
{ name = "ilovemarecon", url = "https://smart.bluefast.horse/catbox-og7mod.png"},
{ name = "lul", url = "https://smart.bluefast.horse/catbox-s36p6q.png"},
{ name = "pickleget", url = "https://smart.bluefast.horse/kissable-hvx6oqh.png"},
{ name = "sunbeam", url = "https://smart.bluefast.horse/catbox-o6jtzj.gif"},
{ name = "berrybased", url = "https://smart.bluefast.horse/smutty-midsfhsywzv.png"},
{ name = "strem", url = "https://smart.bluefast.horse/catbox-0lwds0.png"},
{ name = "kekbeam", url = "https://smart.bluefast.horse/catbox-nq0541.png"},
{ name = "boop", url = "https://smart.bluefast.horse/catbox-najb5q.gif"},
{ name = "boopfast", url = "https://smart.bluefast.horse/catbox-f8ni7g.gif"},
{ name = "boopfaster", url = "https://smart.bluefast.horse/catbox-ljt60a.gif"},
{ name = "boopwaytoofast", url = "https://smart.bluefast.horse/catbox-2iaqcg.gif"},
{ name = "intenseboop", url = "https://smart.bluefast.horse/catbox-0mnq6v.gif"},
{ name = "maximumoverboop", url = "https://smart.bluefast.horse/catbox-sj017c.gif"},
{ name = "yay", url = "https://smart.bluefast.horse/catbox-4xnm1t.gif"},
{ name = "wut", url = "https://smart.bluefast.horse/catbox-jej2yz.png"},
{ name = "wub", url = "https://smart.bluefast.horse/catbox-iiwp97.png"},
{ name = "woonadance", url = "https://smart.bluefast.horse/catbox-vvk0ag.gif"},
{ name = "wiki", url = "https://smart.bluefast.horse/catbox-6ilh64.gif"},
{ name = "wiggle2", url = "https://smart.bluefast.horse/catbox-drs6qv.gif"},
{ name = "windy", url = "https://smart.bluefast.horse/catbox-tsalvd.png"},
{ name = "wink", url = "https://smart.bluefast.horse/catbox-qfyqax.png"},
{ name = "why", url = "https://smart.bluefast.horse/catbox-esxzoj.jpg"},
{ name = "why2", url = "https://smart.bluefast.horse/catbox-s6moiw.gif"},
{ name = "wiggle", url = "https://smart.bluefast.horse/catbox-wdaf9y.gif"},
{ name = "wakemeup", url = "https://smart.bluefast.horse/catbox-ajt5fy.png"},
{ name = "whip", url = "https://smart.bluefast.horse/catbox-7twja2.gif"},
{ name = "twidance2", url = "https://smart.bluefast.horse/catbox-23x66s.gif"},
{ name = "twiggypiggy", url = "https://smart.bluefast.horse/catbox-l22lnu.gif"},
{ name = "twidance", url = "https://smart.bluefast.horse/catbox-fstxko.gif"},
{ name = "unf", url = "https://smart.bluefast.horse/catbox-osu5q1.gif"},
{ name = "twily", url = "https://smart.bluefast.horse/catbox-btk2uw.gif"},
{ name = "trixsweat", url = "https://smart.bluefast.horse/mlprewatch-emotes-trixsweat.png"},
{ name = "trixiebag", url = "https://smart.bluefast.horse/catbox-p8f10q.png"},
{ name = "trixiecite", url = "https://smart.bluefast.horse/smutty-mjswvppkkif.gif"},
{ name = "troll", url = "https://smart.bluefast.horse/catbox-8jqhbz.png"},
{ name = "twicrazy", url = "https://smart.bluefast.horse/mlprewatch-emotes-twicrazy.png"},
{ name = "teacher", url = "https://smart.bluefast.horse/catbox-smzvpd.png"},
{ name = "tism", url = "https://smart.bluefast.horse/catbox-h402s7.gif"},
{ name = "toss", url = "https://smart.bluefast.horse/catbox-w1euh4.gif"},
{ name = "thrust", url = "https://smart.bluefast.horse/catbox-selqzb.gif"},
{ name = "sweetiebounce", url = "https://smart.bluefast.horse/catbox-ibtkoa.gif"},
{ name = "sweat2", url = "https://smart.bluefast.horse/catbox-rvaabu.gif"},
{ name = "sweep", url = "https://smart.bluefast.horse/catbox-tssn5i.gif"},
{ name = "tavi", url = "https://smart.bluefast.horse/catbox-yk4j2w.gif"},
{ name = "swibbles", url = "https://smart.bluefast.horse/mlprewatch-emotes-swibbles.png"},
{ name = "sweat", url = "https://smart.bluefast.horse/catbox-qqxa6y.jpg"},
{ name = "sunbooty", url = "https://smart.bluefast.horse/catbox-dc7bye.gif"},
{ name = "sun", url = "https://smart.bluefast.horse/catbox-e8ae7b.png"},
{ name = "snoot", url = "https://smart.bluefast.horse/catbox-w9cg7m.gif"},
{ name = "spoon", url = "https://smart.bluefast.horse/mlprewatch-emotes-spoon.png"},
{ name = "stomp", url = "https://smart.bluefast.horse/catbox-qaypxu.gif"},
{ name = "spray", url = "https://smart.bluefast.horse/catbox-xj32pu.png"},
{ name = "squee", url = "https://smart.bluefast.horse/catbox-h8l64j.png"},
{ name = "spook", url = "https://smart.bluefast.horse/catbox-qgfesm.gif"},
{ name = "spookdance", url = "https://smart.bluefast.horse/catbox-q7a5u1.gif"},
{ name = "socksual", url = "https://smart.bluefast.horse/catbox-qtdfmx.png"},
{ name = "speeddance", url = "https://smart.bluefast.horse/catbox-l9y4td.gif"},
{ name = "smartpurple", url = "https://smart.bluefast.horse/catbox-ttk392.png"},
{ name = "smug", url = "https://smart.bluefast.horse/catbox-79lrd2.png"},
{ name = "sniff", url = "https://smart.bluefast.horse/catbox-i5v30f.png"},
{ name = "smugilee", url = "https://smart.bluefast.horse/catbox-9q44mx.jpg"},
{ name = "smugpeetzer", url = "https://smart.bluefast.horse/catbox-cf006m.jpg"},
{ name = "smalljack", url = "https://smart.bluefast.horse/catbox-fzfaqi.gif"},
{ name = "slurp", url = "https://smart.bluefast.horse/catbox-wvqwrp.gif"},
{ name = "sillyfilly", url = "https://smart.bluefast.horse/catbox-f75m18.gif"},
{ name = "sip", url = "https://smart.bluefast.horse/catbox-uaqs68.gif"},
{ name = "shootingstars", url = "https://smart.bluefast.horse/catbox-qkr3ab.gif"},
{ name = "shock", url = "https://smart.bluefast.horse/catbox-3y9t1t.png"},
{ name = "silly", url = "https://smart.bluefast.horse/catbox-w3v739.gif"},
{ name = "shrug", url = "https://smart.bluefast.horse/catbox-c3w3yf.jpg"},
{ name = "shiggy", url = "https://smart.bluefast.horse/catbox-w3koc1.png"},
{ name = "scrunch3", url = "https://smart.bluefast.horse/catbox-e94oga.gif"},
{ name = "shid", url = "https://smart.bluefast.horse/catbox-m3rs4a.png"},
{ name = "scrunch2", url = "https://smart.bluefast.horse/catbox-2iimc4.gif"},
{ name = "shakes", url = "https://smart.bluefast.horse/catbox-k210df.gif"},
{ name = "shake", url = "https://smart.bluefast.horse/catbox-m8l0sn.gif"},
{ name = "scoot", url = "https://smart.bluefast.horse/catbox-qxr2g5.gif"},
{ name = "scrunch", url = "https://smart.bluefast.horse/catbox-yz84oj.gif"},
{ name = "screm", url = "https://smart.bluefast.horse/catbox-s9u3or.jpg"},
{ name = "scritch", url = "https://smart.bluefast.horse/mlprewatch-emotes-scritch.gif"},
{ name = "sad", url = "https://smart.bluefast.horse/catbox-bzbckc.gif"},
{ name = "sadtwi", url = "https://smart.bluefast.horse/catbox-wgvoio.gif"},
{ name = "rose", url = "https://smart.bluefast.horse/catbox-kwn8fy.png"},
{ name = "scared", url = "https://smart.bluefast.horse/catbox-mwznrr.png"},
{ name = "scaredchickun", url = "https://smart.bluefast.horse/catbox-q7546o.gif"},
{ name = "rariwiggle", url = "https://smart.bluefast.horse/mlprewatch-emotes-rariwiggle.gif"},
{ name = "rock", url = "https://smart.bluefast.horse/catbox-m5ldih.png"},
{ name = "rekt", url = "https://smart.bluefast.horse/catbox-4yjq4a.gif"},
{ name = "riff", url = "https://smart.bluefast.horse/catbox-j7iv3x.png"},
{ name = "razzledazzle", url = "https://smart.bluefast.horse/catbox-lrwnp6.png"},
{ name = "rarasmug", url = "https://smart.bluefast.horse/mlprewatch-emotes-rarasmug.png"},
{ name = "rarijam", url = "https://smart.bluefast.horse/catbox-5k35cu.gif"},
{ name = "rarinom", url = "https://smart.bluefast.horse/catbox-qcga2d.gif"},
{ name = "rapgod", url = "https://smart.bluefast.horse/catbox-jp9une.png"},
{ name = "rarara", url = "https://smart.bluefast.horse/catbox-wkc5q6.gif"},
{ name = "purp", url = "https://smart.bluefast.horse/catbox-4ciiiu.gif"},
{ name = "rape", url = "https://smart.bluefast.horse/catbox-iyuxe2.jpg"},
{ name = "racistbarn", url = "https://smart.bluefast.horse/catbox-pwssui.png"},
{ name = "purpledance", url = "https://smart.bluefast.horse/mlprewatch-emotes-purpledance.gif"},
{ name = "quiet", url = "https://smart.bluefast.horse/catbox-6nxwq6.png"},
{ name = "pony", url = "https://smart.bluefast.horse/mlprewatch-emotes-pony.jpg"},
{ name = "pressure", url = "https://smart.bluefast.horse/catbox-q31z2h.gif"},
{ name = "promise", url = "https://smart.bluefast.horse/catbox-nquewq.gif"},
{ name = "professional", url = "https://smart.bluefast.horse/catbox-k6c5pq.gif"},
{ name = "partygirl", url = "https://smart.bluefast.horse/catbox-ceiwgp.gif"},
{ name = "ponka", url = "https://smart.bluefast.horse/catbox-8772wd.png"},
{ name = "peeved", url = "https://smart.bluefast.horse/mlprewatch-emotes-peeved.png"},
{ name = "ponk", url = "https://smart.bluefast.horse/catbox-rqvud9.png"},
{ name = "partysoft", url = "https://smart.bluefast.horse/catbox-cx6mhs.gif"},
{ name = "partyhard", url = "https://smart.bluefast.horse/catbox-82whn6.gif"},
{ name = "peetzer", url = "https://smart.bluefast.horse/catbox-cl0ur0.png"},
{ name = "notimpressed", url = "https://smart.bluefast.horse/catbox-kis44m.png"},
{ name = "notcanon", url = "https://smart.bluefast.horse/catbox-r14ked.png"},
{ name = "ooober", url = "https://smart.bluefast.horse/catbox-g4onc8.png"},
{ name = "nom", url = "https://smart.bluefast.horse/catbox-85a66l.gif"},
{ name = "moonbooty", url = "https://smart.bluefast.horse/catbox-d1elut.gif"},
{ name = "meh", url = "https://smart.bluefast.horse/catbox-xcd89q.png"},
{ name = "moondance", url = "https://smart.bluefast.horse/catbox-0vhthd.gif"},
{ name = "neet", url = "https://smart.bluefast.horse/catbox-4bmr4p.png"},
{ name = "maresspin", url = "https://smart.bluefast.horse/catbox-2ls2c7.gif"},
{ name = "maresfaster", url = "https://smart.bluefast.horse/catbox-6i8dbb.gif"},
{ name = "maresfast", url = "https://smart.bluefast.horse/catbox-2cl76j.gif"},
{ name = "march", url = "https://smart.bluefast.horse/catbox-vww0w9.gif"},
{ name = "marble", url = "https://smart.bluefast.horse/mlprewatch-emotes-marble.gif"},
{ name = "mare", url = "https://smart.bluefast.horse/catbox-072a86.gif"},
{ name = "mares", url = "https://smart.bluefast.horse/catbox-w2xw8p.gif"},
{ name = "loira", url = "https://smart.bluefast.horse/catbox-f4jf1s.gif"},
{ name = "laughingmares", url = "https://smart.bluefast.horse/catbox-8ed03p.gif"},
{ name = "lulra", url = "https://smart.bluefast.horse/catbox-siq20c.png"},
{ name = "lewd", url = "https://smart.bluefast.horse/catbox-qgb6rj.jpg"},
{ name = "limey", url = "https://smart.bluefast.horse/catbox-b7s9tf.png"},
{ name = "kickyhooves", url = "https://smart.bluefast.horse/catbox-xencrx.gif"},
{ name = "kek2", url = "https://smart.bluefast.horse/catbox-k76ywl.gif"},
{ name = "larson", url = "https://smart.bluefast.horse/catbox-hl8ftx.gif"},
{ name = "kek", url = "https://smart.bluefast.horse/catbox-akxp1u.gif"},
{ name = "kek3", url = "https://smart.bluefast.horse/catbox-ecrfov.gif"},
{ name = "incest", url = "https://smart.bluefast.horse/catbox-76iki5.png"},
{ name = "juicebox", url = "https://smart.bluefast.horse/catbox-yrykr3.png"},
{ name = "jew", url = "https://smart.bluefast.horse/catbox-r3vkl9.gif"},
{ name = "hug", url = "https://smart.bluefast.horse/mlprewatch-emotes-hug.png"},
{ name = "horse", url = "https://smart.bluefast.horse/catbox-yrlptn.jpg"},
{ name = "hitwi", url = "https://smart.bluefast.horse/catbox-hm7430.gif"},
{ name = "horn", url = "https://smart.bluefast.horse/catbox-yszf0h.gif"},
{ name = "hoofykicks", url = "https://smart.bluefast.horse/catbox-j6r95a.gif"},
{ name = "honesty", url = "https://smart.bluefast.horse/catbox-q4ag7b.gif"},
{ name = "hoof", url = "https://smart.bluefast.horse/catbox-jsr2da.png"},
{ name = "grounded", url = "https://smart.bluefast.horse/catbox-a6oaux.png"},
{ name = "hen", url = "https://smart.bluefast.horse/catbox-urmxn8.gif"},
{ name = "glutes", url = "https://smart.bluefast.horse/catbox-gyk6cn.gif"},
{ name = "gottagofast", url = "https://smart.bluefast.horse/catbox-w4htwh.png"},
{ name = "glim", url = "https://smart.bluefast.horse/catbox-eelol8.gif"},
{ name = "gasp", url = "https://smart.bluefast.horse/catbox-7uc5if.png"},
{ name = "giddyup", url = "https://smart.bluefast.horse/catbox-de8vrp.png"},
{ name = "giwtwm", url = "https://smart.bluefast.horse/catbox-gciszc.png"},
{ name = "gallop", url = "https://smart.bluefast.horse/mlprewatch-emotes-gallop.gif"},
{ name = "forever", url = "https://smart.bluefast.horse/catbox-p0x6ba.png"},
{ name = "fun2", url = "https://smart.bluefast.horse/catbox-jwbbeh.gif"},
{ name = "fusroyay", url = "https://smart.bluefast.horse/catbox-9sq2ed.png"},
{ name = "france", url = "https://smart.bluefast.horse/catbox-tqbnul.gif"},
{ name = "fun", url = "https://smart.bluefast.horse/catbox-4xonbs.gif"},
{ name = "flutterdance", url = "https://smart.bluefast.horse/catbox-mh5dpw.gif"},
{ name = "fluttertree", url = "https://smart.bluefast.horse/catbox-i5jqf8.png"},
{ name = "flutternom", url = "https://smart.bluefast.horse/catbox-trjqmy.gif"},
{ name = "floss", url = "https://smart.bluefast.horse/catbox-xqkojn.gif"},
{ name = "flutterbitch", url = "https://smart.bluefast.horse/catbox-ypswzv.png"},
{ name = "fillybop", url = "https://smart.bluefast.horse/catbox-xfiork.gif"},
{ name = "firebutt", url = "https://smart.bluefast.horse/catbox-rh8kdz.png"},
{ name = "feels", url = "https://smart.bluefast.horse/catbox-1tbpm5.gif"},
{ name = "fetish", url = "https://smart.bluefast.horse/catbox-dz8ixx.jpg"},
{ name = "eyebrow", url = "https://smart.bluefast.horse/catbox-wznxmx.gif"},
{ name = "faggot", url = "https://smart.bluefast.horse/catbox-j5yf7m.png"},
{ name = "fabulous", url = "https://smart.bluefast.horse/catbox-f9mxwd.gif"},
{ name = "faust", url = "https://smart.bluefast.horse/mlprewatch-emotes-faust.png"},
{ name = "excited", url = "https://smart.bluefast.horse/catbox-vlbl62.gif"},
{ name = "excite", url = "https://smart.bluefast.horse/catbox-g3xart.gif"},
{ name = "egghead", url = "https://smart.bluefast.horse/mlprewatch-emotes-egghead.png"},
{ name = "eat", url = "https://smart.bluefast.horse/catbox-dam8n7.gif"},
{ name = "engineer", url = "https://smart.bluefast.horse/ponybooru-1526089-thumb_tiny.png"},
{ name = "equestria", url = "https://smart.bluefast.horse/catbox-ntmsfg.gif"},
{ name = "donkdance", url = "https://smart.bluefast.horse/pinkhorse-prance.gif"},
{ name = "dt", url = "https://smart.bluefast.horse/mlprewatch-emotes-dt.png"},
{ name = "donk", url = "https://smart.bluefast.horse/catbox-7km4hr.png"},
{ name = "doot", url = "https://smart.bluefast.horse/catbox-kenlfx.gif"},
{ name = "doubled", url = "https://smart.bluefast.horse/catbox-iwef0j.png"},
{ name = "dog", url = "https://smart.bluefast.horse/catbox-iwouh3.gif"},
{ name = "diggingforgold", url = "https://smart.bluefast.horse/mlprewatch-emotes-diggingforgold.gif"},
{ name = "derpflip", url = "https://smart.bluefast.horse/catbox-jzwly2.gif"},
{ name = "diamond", url = "https://smart.bluefast.horse/catbox-mn2w9c.png"},
{ name = "derpdance", url = "https://smart.bluefast.horse/catbox-iq1h2j.gif"},
{ name = "dashiewashie", url = "https://smart.bluefast.horse/catbox-wg333c.gif"},
{ name = "darling", url = "https://smart.bluefast.horse/catbox-r67ddz.gif"},
{ name = "derp", url = "https://smart.bluefast.horse/catbox-8g6khc.png"},
{ name = "datplot", url = "https://smart.bluefast.horse/catbox-to5yss.png"},
{ name = "ded", url = "https://smart.bluefast.horse/catbox-sa24wr.png"},
{ name = "dangerzone", url = "https://smart.bluefast.horse/catbox-vy6600.jpg"},
{ name = "dansen", url = "https://smart.bluefast.horse/catbox-zcq7mq.gif"},
{ name = "dance11", url = "https://smart.bluefast.horse/catbox-9n3ytd.gif"},
{ name = "dance10", url = "https://smart.bluefast.horse/catbox-h47wdr.gif"},
{ name = "dance9", url = "https://smart.bluefast.horse/catbox-a4f4em.gif"},
{ name = "dance4", url = "https://smart.bluefast.horse/catbox-wlcme1.gif"},
{ name = "dance5", url = "https://smart.bluefast.horse/catbox-p1i8ak.gif"},
{ name = "dance7", url = "https://smart.bluefast.horse/catbox-fo199x.gif"},
{ name = "dance6", url = "https://smart.bluefast.horse/catbox-215xim.gif"},
{ name = "dance8", url = "https://smart.bluefast.horse/catbox-9dtvmw.gif"},
{ name = "crusty", url = "https://smart.bluefast.horse/catbox-lfhvhl.gif"},
{ name = "dance3", url = "https://smart.bluefast.horse/catbox-xk1rgy.gif"},
{ name = "dance2", url = "https://smart.bluefast.horse/catbox-4xvkcw.gif"},
{ name = "dance", url = "https://smart.bluefast.horse/catbox-snfxs5.gif"},
{ name = "creatura", url = "https://smart.bluefast.horse/mlprewatch-emotes-creatura.gif"},
{ name = "communism", url = "https://smart.bluefast.horse/catbox-424qip.png"},
{ name = "coof", url = "https://smart.bluefast.horse/catbox-ipsu38.gif"},
{ name = "cozy", url = "https://smart.bluefast.horse/catbox-jiaz96.png"},
{ name = "clop", url = "https://smart.bluefast.horse/catbox-iiup6n.gif"},
{ name = "comfytwi", url = "https://smart.bluefast.horse/catbox-wsqib5.png"},
{ name = "clap", url = "https://smart.bluefast.horse/catbox-9o3ksy.gif"},
{ name = "carrotnom", url = "https://smart.bluefast.horse/catbox-g25777.gif"},
{ name = "clop2", url = "https://smart.bluefast.horse/mlprewatch-emotes-clop2.jpg"},
{ name = "cans.wav", url = "https://smart.bluefast.horse/cymotes-047bdbccaa72434db8a88e75852e7db1.gif"},
{ name = "cheer", url = "https://smart.bluefast.horse/catbox-2r4j1h.gif"},
{ name = "cane", url = "https://smart.bluefast.horse/derpi-1260972-small.png"},
{ name = "coco", url = "https://smart.bluefast.horse/catbox-b17ex5.png"},
{ name = "chicken", url = "https://smart.bluefast.horse/catbox-sn4h2l.png"},
{ name = "cider", url = "https://smart.bluefast.horse/catbox-82hsm3.gif"},
{ name = "cake", url = "https://smart.bluefast.horse/catbox-cmj8pw.png"},
{ name = "brush", url = "https://smart.bluefast.horse/catbox-kquwl4.gif"},
{ name = "bug", url = "https://smart.bluefast.horse/catbox-3ezvnr.gif"},
{ name = "burra", url = "https://smart.bluefast.horse/puush-cyXaB.png"},
{ name = "/)", url = "https://smart.bluefast.horse/catbox-a1k9di.jpg"},
{ name = "bueno", url = "https://smart.bluefast.horse/catbox-l2tzgs.png"},
{ name = "bread", url = "https://smart.bluefast.horse/catbox-mzhajg.jpg"},
{ name = "boner", url = "https://smart.bluefast.horse/catbox-f64ng6.gif"},
{ name = "brap", url = "https://smart.bluefast.horse/catbox-dvahkc.gif"},
{ name = "bon3", url = "https://smart.bluefast.horse/catbox-ws13dl.png"},
{ name = "booty", url = "https://smart.bluefast.horse/catbox-9quaji.gif"},
{ name = "bon2", url = "https://smart.bluefast.horse/catbox-zve8dv.gif"},
{ name = "blue", url = "https://smart.bluefast.horse/catbox-hqunsd.gif"},
{ name = "bloom", url = "https://smart.bluefast.horse/catbox-ef2xoe.gif"},
{ name = "bluefast", url = "https://smart.bluefast.horse/catbox-8abd8z.png"},
{ name = "blini", url = "https://smart.bluefast.horse/catbox-g2mc0f.png"},
{ name = "bon", url = "https://smart.bluefast.horse/catbox-xauewm.png"},
{ name = "birthday", url = "https://smart.bluefast.horse/catbox-q4c789.gif"},
{ name = "berryspooky", url = "https://smart.bluefast.horse/catbox-a483tr.gif"},
{ name = "beegloira", url = "https://smart.bluefast.horse/catbox-xywwkp.gif"},
{ name = "berrycute", url = "https://smart.bluefast.horse/catbox-qidz50.png"},
{ name = "belle", url = "https://smart.bluefast.horse/catbox-skwycn.gif"},
{ name = "beep", url = "https://smart.bluefast.horse/catbox-salwee.png"},
{ name = "belli", url = "https://smart.bluefast.horse/catbox-bz17u4.gif"},
{ name = "banjo", url = "https://smart.bluefast.horse/catbox-d7x18c.gif"},
{ name = "barrelroll", url = "https://smart.bluefast.horse/catbox-exv91z.gif"},
{ name = "bee", url = "https://smart.bluefast.horse/catbox-r4gvfv.png"},
{ name = "balloons", url = "https://smart.bluefast.horse/catbox-3awoni.png"},
{ name = "based", url = "https://smart.bluefast.horse/catbox-n5rgkf.png"},
{ name = "babs", url = "https://smart.bluefast.horse/catbox-9namy8.png"},
{ name = "applehop", url = "https://smart.bluefast.horse/catbox-7ukeop.gif"},
{ name = "appuldance", url = "https://smart.bluefast.horse/catbox-junej3.gif"},
{ name = "ajscrunch", url = "https://smart.bluefast.horse/catbox-mxa1m9.gif"},
{ name = "ajbang", url = "https://smart.bluefast.horse/catbox-dvg2ee.gif"},
{ name = "420", url = "https://smart.bluefast.horse/catbox-fzlsbg.png"},
{ name = "zigger", url = "https://smart.bluefast.horse/catbox-6zgmf3.gif"},
{ name = "yellowquiet", url = "https://smart.bluefast.horse/catbox-e5ocbr.png"},
{ name = "2lewd", url = "https://smart.bluefast.horse/catbox-9pm6lf.gif"},
{ name = "dashierock", url = "https://smart.bluefast.horse/cymotes-f46bea3a82c69c5771fdec02f18a2963.gif"},
{ name = "amogus", url = "https://smart.bluefast.horse/smutty-mfbhgzfmene.png"},
{ name = "happi", url = "https://smart.bluefast.horse/smutty-mkrgorkhnyd.gif"},
{ name = "linky", url = "https://smart.bluefast.horse/smutty-mheaiettoar.png"},
{ name = "derp.wave", url = "https://smart.bluefast.horse/derpi-1143330.gif"},
{ name = "dashplot", url = "https://smart.bluefast.horse/smutty-mjaohuryqfw.gif"},
{ name = "muffin.time", url = "https://smart.bluefast.horse/blogspot--bGhV6Q7Y9KA-Vpy9atOw7jI-AAAAAAACf98-W9iVHklwmB4-s640-17.gif"},
{ name = "curious", url = "https://smart.bluefast.horse/derpi-2891336-large.png"},
{ name = "good.show", url = "https://smart.bluefast.horse/discord-772048401344364565-773103969232879626-small.png"},
{ name = "what", url = "https://smart.bluefast.horse/derpi-667689-small.png"},
{ name = "ploota", url = "https://smart.bluefast.horse/smutty-minquwelfnv.png"},
{ name = "3", url = "https://smart.bluefast.horse/pinkhorse-colon.three.png"},
{ name = "tired", url = "https://smart.bluefast.horse/derpi-3021841.png"},
{ name = "l", url = "https://smart.bluefast.horse/smutty-mlcwymjkrjc.png"},
{ name = "honk", url = "https://smart.bluefast.horse/smutty-mlcxciegdxq.gif"},
{ name = "ciderdance", url = "https://smart.bluefast.horse/smutty-menxufllquf.gif"},
{ name = "drdplot", url = "https://smart.bluefast.horse/smutty-mjapfgrjvel.gif"},
{ name = "niggermare", url = "https://smart.bluefast.horse/smutty-mbtjavhniaz.png"},
{ name = "marenigger", url = "https://smart.bluefast.horse/smutty-mldjfyrldsa.png"},
{ name = "marenigga", url = "https://smart.bluefast.horse/smutty-mldjidinogn.gif"},
{ name = "moonbeam", url = "https://smart.bluefast.horse/smutty-mjqombxmtij.gif"},
{ name = "faghug", url = "https://smart.bluefast.horse/smutty-mjdrbtgkdaw.png"},
{ name = "reee", url = "https://smart.bluefast.horse/derpi-1700122.png"},
{ name = "berrywink", url = "https://smart.bluefast.horse/smutty-mhkdzjkriko.png"},
{ name = "tegmun", url = "https://smart.bluefast.horse/smutty-mldskdgpcjr.png"},
{ name = "books", url = "https://smart.bluefast.horse/derpi-98992-small.png"},
{ name = "sisi", url = "https://smart.bluefast.horse/smutty-mibdrveswfx.png"},
{ name = "sleepy", url = "https://smart.bluefast.horse/ponerpics-719725.png"},
{ name = "thursday", url = "https://smart.bluefast.horse/twibooru-2696824-large.jpeg"},
{ name = "roseclone", url = "https://smart.bluefast.horse/pomf2-a162ewp.png"},
{ name = "tolly", url = "https://smart.bluefast.horse/smutty-mgnxdmfosbs.png"},
{ name = "stretch", url = "https://smart.bluefast.horse/discord-988225992306880584-989677952558047262-el_stretch.png"},
{ name = "pinkwink", url = "https://smart.bluefast.horse/discord-988225992306880584-989678895005597706-PinkmojiWink.png"},
{ name = "drip", url = "https://smart.bluefast.horse/discord-988225992306880584-989711932456071218-unknown.png"},
{ name = "numget", url = "https://smart.bluefast.horse/smutty-mhyysqdcmkt.png"},
{ name = "numgethd", url = "https://smart.bluefast.horse/smutty-mhwsbglafnw.png"},
{ name = "ponktoy", url = "https://smart.bluefast.horse/smutty-mhzunmkmjrz.png"},
{ name = "pinkie.works", url = "https://smart.bluefast.horse/derpi-1057043-thumb.gif"},
{ name = "ponkwut", url = "https://smart.bluefast.horse/smutty-miaojwadfjq.png"},
{ name = "swatch", url = "https://smart.bluefast.horse/smutty-miaoyqcoyap.png"},
{ name = "iwtcird", url = "https://smart.bluefast.horse/catbox-ecqbfn.png"},
{ name = "applause", url = "https://smart.bluefast.horse/smutty-mhqdvqyirjx.gif"},
{ name = "grumpbon", url = "https://smart.bluefast.horse/smutty-midqxercmtm.png"},
{ name = "faejam", url = "https://smart.bluefast.horse/smutty-migpygzqtjk.gif"},
{ name = "twiggle", url = "https://smart.bluefast.horse/smutty-miisyeqeqlu.gif"},
{ name = "heh", url = "https://smart.bluefast.horse/smutty-miisykfjvtr.png"},
{ name = "salute", url = "https://smart.bluefast.horse/smutty-miisyvacidq.png"},
{ name = "ote", url = "https://smart.bluefast.horse/smutty-miityfeilzb.gif"},
{ name = "gun", url = "https://smart.bluefast.horse/smutty-miityxutwva.gif"},
{ name = "borked", url = "https://smart.bluefast.horse/smutty-mijdyrcqiyh.gif"},
{ name = "brick", url = "https://smart.bluefast.horse/smutty-mikowlexuyp.jpg"},
{ name = "sunbale", url = "https://smart.bluefast.horse/smutty-mimilynxkpl.gif"},
{ name = "hi5", url = "https://smart.bluefast.horse/smutty-mipkgybehfp.gif"},
{ name = "huh", url = "https://smart.bluefast.horse/smutty-mipkslxqgpg.png"},
{ name = "ponkster", url = "https://smart.bluefast.horse/smutty-mipkxeellgw.gif"},
{ name = "anonjam", url = "https://smart.bluefast.horse/smutty-miplecziqfp.gif"},
{ name = "blender", url = "https://smart.bluefast.horse/twibooru-1231554.png"},
{ name = "gimp", url = "https://smart.bluefast.horse/smutty-midrxjswvka.png"},
{ name = "brain", url = "https://smart.bluefast.horse/pixy-4452532.jpg"},
{ name = "me", url = "https://smart.bluefast.horse/smutty-mjiwnkpxgeo.jpg"},
{ name = "shh", url = "https://smart.bluefast.horse/ytimg-X8pYrApj4ZA.jpg"},
{ name = "shhh", url = "https://smart.bluefast.horse/smutty-mjjiwjavzho.png"},
{ name = "when", url = "https://smart.bluefast.horse/smutty-mjlbvpqnsvk.jpg"},
{ name = "seethe", url = "https://smart.bluefast.horse/smutty-mjlyjobtuhu.gif"},
{ name = "awooga", url = "https://smart.bluefast.horse/smutty-mdqcrjnzqbv.png"},
{ name = "appleshrug", url = "https://smart.bluefast.horse/smutty-mjowmzxoosc.png"},
{ name = "amre", url = "https://smart.bluefast.horse/smutty-mjoxgkakmej.gif"},
{ name = "wine", url = "https://smart.bluefast.horse/smutty-mjoxkzuujfx.gif"},
{ name = "sicko", url = "https://smart.bluefast.horse/smutty-mjoyeqeuqbz.png"},
{ name = "sadponk", url = "https://smart.bluefast.horse/smutty-mjoyevbokcl.png"},
{ name = "hi4", url = "https://smart.bluefast.horse/smutty-mjoyfccbkzn.gif"},
{ name = "headbang", url = "https://smart.bluefast.horse/smutty-mfzpsfqmxsz.gif"},
{ name = "ambulance", url = "https://smart.bluefast.horse/smutty-mjoyfnfymti.png"},
{ name = "sleep", url = "https://smart.bluefast.horse/smutty-mjoyznncdxa.png"},
{ name = "angy", url = "https://smart.bluefast.horse/smutty-mjozixllnnf.jpg"},
{ name = "ponky", url = "https://smart.bluefast.horse/smutty-mjozjcboryj.jpg"},
{ name = "igotyourip", url = "https://smart.bluefast.horse/smutty-mjudrjgdfvn.gif"},
{ name = "pwiggle", url = "https://smart.bluefast.horse/smutty-mjsbabcbebd.gif"},
{ name = "ruf", url = "https://smart.bluefast.horse/smutty-mjxckafdewa.gif"},
{ name = "twhy", url = "https://smart.bluefast.horse/smutty-mjlcfbwkgjf.gif"},
{ name = "twidance1", url = "https://smart.bluefast.horse/smutty-mjxdetrmyeu.gif"},
{ name = "delet", url = "https://smart.bluefast.horse/smutty-mjxdhuxcomk.jpg"},
{ name = "marewave", url = "https://smart.bluefast.horse/smutty-mjxdittnijv.gif"},
{ name = "blahblah", url = "https://smart.bluefast.horse/smutty-mjxfdtglzyc.gif"},
{ name = "welcome", url = "https://smart.bluefast.horse/smutty-mjxftqoozql.png"},
{ name = "swears", url = "https://smart.bluefast.horse/catbox-ezfemh.png"},
{ name = "derpbop", url = "https://smart.bluefast.horse/catbox-25aw4w.gif"},
{ name = "huh.2", url = "https://smart.bluefast.horse/catbox-1j83wq.png"},
{ name = "twihuh", url = "https://smart.bluefast.horse/catbox-m7vvpz.jpeg"},
{ name = "fillyposting", url = "https://smart.bluefast.horse/smutty-mljgglwhmzm.png"},
{ name = "pwiggle2", url = "https://smart.bluefast.horse/catbox-956p8x.gif"},
{ name = "maud", url = "https://smart.bluefast.horse/derpi-1696795.gif"},
{ name = "numgetdance", url = "https://smart.bluefast.horse/smutty-mkhysxamcen.gif"},
{ name = "yaybeam", url = "https://smart.bluefast.horse/catbox-bjasrm.png"},
{ name = "suneyes", url = "https://smart.bluefast.horse/catbox-xjvyes.png"},
{ name = "poomp", url = "https://smart.bluefast.horse/smutty-miunitqsgpc.gif"},
{ name = "numswet", url = "https://smart.bluefast.horse/catbox-s3ps48.jpg"},
{ name = "burmger", url = "https://smart.bluefast.horse/catbox-rb0myz.png"},
{ name = "carlos", url = "https://smart.bluefast.horse/ponerpics-6887472-large.png"},
{ name = "snowbeam", url = "https://smart.bluefast.horse/kissable-eg8f7r6.gif"},
{ name = "psst", url = "https://smart.bluefast.horse/kissable-8t0mj0qg.gif"},
{ name = "movietime", url = "https://smart.bluefast.horse/catbox-dbhd9o.png"},
{ name = "matineedance", url = "https://smart.bluefast.horse/catbox-pdmz92.gif"},
{ name = "soireedance", url = "https://smart.bluefast.horse/catbox-7t9thk.gif"},
{ name = "gander", url = "https://smart.bluefast.horse/catbox-ikvyws.png"},
{ name = "waitwhat", url = "https://smart.bluefast.horse/kissable-qp0xch7.gif"},
{ name = "susget", url = "https://smart.bluefast.horse/pomf2-j6x67i2.png"},
{ name = "bonstroke", url = "https://smart.bluefast.horse/kissable-5jenere.gif"},
{ name = "wow", url = "https://smart.bluefast.horse/smutty-mjsbadzgcxl.png"},
{ name = "yowza", url = "https://smart.bluefast.horse/catbox-rc7mu1.png"},
{ name = "noice", url = "https://smart.bluefast.horse/kissable-dsg9bvs.png"},
{ name = "numparty", url = "https://smart.bluefast.horse/catbox-xty5qe.png"},
{ name = "pray", url = "https://smart.bluefast.horse/catbox-m5jyha.png"},
{ name = "orbs", url = "https://smart.bluefast.horse/catbox-iy42ez.gif"},
{ name = "numorbs", url = "https://smart.bluefast.horse/catbox-b19epj.gif"},
{ name = "superhyperpwiggle", url = "https://smart.bluefast.horse/mlpcon-ludicrousspeedpwiggle.gif"},
{ name = "westget", url = "https://smart.bluefast.horse/catbox-cw5sha.jpg"},
{ name = "berryshock", url = "https://smart.bluefast.horse/catbox-1tyc8v.gif"},
{ name = "oootwi", url = "https://smart.bluefast.horse/catbox-oxhy92.png"},
{ name = "noiver", url = "https://smart.bluefast.horse/catbox-r1iq3n.png"},
{ name = "grump", url = "https://smart.bluefast.horse/catbox-bd17od.gif"},
{ name = "hoofgasp", url = "https://smart.bluefast.horse/catbox-v1y0cp.png"},
{ name = "popcorn", url = "https://smart.bluefast.horse/catbox-d4z8y4.gif"},
{ name = "ant", url = "https://smart.bluefast.horse/catbox-utbcm9.jpg"},
{ name = "godforbid", url = "https://smart.bluefast.horse/catbox-g48o9u.png"},
{ name = "popcorn2", url = "https://smart.bluefast.horse/ponerpics-121996.gif"},
{ name = "mauddance", url = "https://smart.bluefast.horse/catbox-sm0448.gif"},
{ name = "limeydance", url = "https://smart.bluefast.horse/catbox-527hiz.gif"},
{ name = "really", url = "https://smart.bluefast.horse/smutty-mhzhlswmtfw.gif"},
{ name = "numgetbeam", url = "https://smart.bluefast.horse/catbox-ry6el2.png"},
{ name = "cheerget", url = "https://smart.bluefast.horse/pomf2-qkbvqtz.gif"},
{ name = "hi3", url = "https://smart.bluefast.horse/derpi-3197938.png"},
{ name = "butget", url = "https://smart.bluefast.horse/catbox-5ah3fo.png"},
{ name = "bewilderment", url = "https://smart.bluefast.horse/pomf2-lm949og4.png"},
{ name = "rumpa", url = "https://smart.bluefast.horse/derpi-2467782.png"},
{ name = "loud2", url = "https://smart.bluefast.horse/catbox-koyvll.png"},
{ name = "kiss", url = "https://smart.bluefast.horse/catbox-5rmlo9.gif"},
{ name = "numderdasea", url = "https://smart.bluefast.horse/catbox-7byfg5.jpg"},
{ name = "rapget", url = "https://smart.bluefast.horse/catbox-ssnuo3.png"},
{ name = "frenchget", url = "https://smart.bluefast.horse/kissable-lwcyo5g.png"},
{ name = "hmmget", url = "https://smart.bluefast.horse/kissable-1ifx2g.png"},
{ name = "numblink", url = "https://smart.bluefast.horse/catbox-wojcsj.gif"},
{ name = "fishbowlget", url = "https://smart.bluefast.horse/catbox-1se4c0.png"},
{ name = "saiyanget", url = "https://smart.bluefast.horse/kissable-cbp5tjwl.jpeg"},
{ name = "sadget", url = "https://smart.bluefast.horse/catbox-fpdmo8.png"},
{ name = "flyget", url = "https://smart.bluefast.horse/catbox-u1dygg.gif"},
{ name = "boopget", url = "https://smart.bluefast.horse/catbox-3o8f8p.png"},
{ name = "trixget", url = "https://smart.bluefast.horse/catbox-kghyl3.png"},
{ name = "streamerget", url = "https://smart.bluefast.horse/catbox-3vngrc.png"},
{ name = "lostget", url = "https://smart.bluefast.horse/catbox-pkjp50.png"},
{ name = "wortget", url = "https://smart.bluefast.horse/catbox-v167qf.png"},
{ name = "gruntget", url = "https://smart.bluefast.horse/catbox-5hrf9x.png"},
{ name = "numyay", url = "https://smart.bluefast.horse/pomf2-d5i0yb22.png"},
{ name = "skibidi", url = "https://smart.bluefast.horse/pomf2-5xu52tep.png"},
{ name = "wheeze", url = "https://smart.bluefast.horse/catbox-rzm9tt.png"},
{ name = "furget", url = "https://smart.bluefast.horse/catbox-q79mj7.png"},
{ name = "lemon", url = "https://smart.bluefast.horse/catbox-hukjg8.gif"},
{ name = "lemonantget", url = "https://smart.bluefast.horse/catbox-1qg1nq.png"},
{ name = "blindget", url = "https://smart.bluefast.horse/pomf2-2kfgwc0p.jpg"},
{ name = "lewdget", url = "https://smart.bluefast.horse/pomf2-m8pfyuj.png"},
{ name = "teeth", url = "https://smart.bluefast.horse/catbox-lerz7w.png"},
{ name = "numver", url = "https://smart.bluefast.horse/pomf2-ourm0m4i.png"},
{ name = "donkbeam", url = "https://smart.bluefast.horse/catbox-ksn3nt.png"},
{ name = "mirrorget", url = "https://smart.bluefast.horse/pomf2-ubwqfz7s.png"},
{ name = "numant", url = "https://smart.bluefast.horse/catbox-4uwlao.png"},
{ name = "bwoomp", url = "https://smart.bluefast.horse/catbox-26bgb9.gif"},
{ name = "antget", url = "https://smart.bluefast.horse/catbox-4io0dd.png"},
{ name = "haloget", url = "https://smart.bluefast.horse/catbox-2snmm1.png"},
{ name = "dwarfget", url = "https://smart.bluefast.horse/catbox-gms16n.png"},
{ name = "fillyhug", url = "https://smart.bluefast.horse/catbox-5wxs7s.png"},
{ name = "fillyham", url = "https://smart.bluefast.horse/catbox-bm8m6z.gif"},
{ name = "sirsget", url = "https://smart.bluefast.horse/catbox-ram5jd.png"},
{ name = "starebeam", url = "https://smart.bluefast.horse/catbox-swyefl.png"},
{ name = "numblep", url = "https://smart.bluefast.horse/catbox-wvy3wo.png"},
{ name = "iwtcil", url = "https://smart.bluefast.horse/catbox-4bu6d4.png"},
{ name = "ponkflowersniff", url = "https://smart.bluefast.horse/ponerpics-2756951.gif"},
{ name = "belli2", url = "https://smart.bluefast.horse/catbox-qk7dsm.gif"},
{ name = "exciteget", url = "https://smart.bluefast.horse/catbox-olbvs8.gif"},
{ name = "ilovethem", url = "https://smart.bluefast.horse/catbox-9rgtoy.png"},
{ name = "linkystand", url = "https://smart.bluefast.horse/catbox-mpw5sa.gif"},
{ name = "sleepylinky", url = "https://smart.bluefast.horse/catbox-hlh938.gif"},
{ name = "linkydance", url = "https://smart.bluefast.horse/catbox-f2smgz.gif"},
{ name = "berrydance", url = "https://smart.bluefast.horse/catbox-nmoghe.gif"},
{ name = "berryyay", url = "https://smart.bluefast.horse/catbox-vcuyb6.png"},
{ name = "hi2", url = "https://smart.bluefast.horse/catbox-5wcqvw.gif"},
{ name = "lyrant", url = "https://smart.bluefast.horse/catbox-qnbrze.png"},
{ name = "boomstick", url = "https://smart.bluefast.horse/catbox-kykcte.jpg"},
{ name = "loud", url = "https://smart.bluefast.horse/catbox-48dpaq.png"},
{ name = "strawbeam", url = "https://smart.bluefast.horse/catbox-6e89rv.png"},
{ name = "strawberrysmug", url = "https://smart.bluefast.horse/catbox-l798by.gif"},
{ name = "aikino", url = "https://smart.bluefast.horse/catbox-hqz4bh.png"},
{ name = "aislop", url = "https://smart.bluefast.horse/catbox-mrnvkf.png"},
{ name = "smileyspin", url = "https://files.catbox.moe/uhzx5a.gif"},
{ name = "smileyspinfast", url = "https://files.catbox.moe/0x5a1f.gif"},
{ name = "smileyspinfaster", url = "https://files.catbox.moe/lx7pwe.gif"},
{ name = "X", url = "https://pomf2.lain.la/f/8rbbwfp7.png"},
{ name = "pog", url = "https://pomf2.lain.la/f/qxxlucac.png"},
{ name = "plootalive", url = "https://pomf2.lain.la/f/k588gnar.png"},
{ name = "smiley", url = "https://pomf2.lain.la/f/bvwfymb6.png"},
{ name = "just", url = "https://pomf2.lain.la/f/m0spoxl.png"},
{ name = "glyraphid", url = "https://pomf2.lain.la/f/qugc4thm.png"},
{ name = "eee", url = "https://smart.bluefast.horse/catbox-me64hj.gif"},
{ name = "crocs", url = "https://smart.bluefast.horse/catbox-kaov59.png"},
{ name = "aerobics", url = "https://smart.bluefast.horse/catbox-6vfr89.gif"},
{ name = "faint", url = "https://smart.bluefast.horse/catbox-cucnew.gif"},
{ name = "twinklehop", url = "https://smart.bluefast.horse/catbox-7zl3i9.gif"},
{ name = "dapperget", url = "https://pomf2.lain.la/f/blqu3vtz.png"},
{ name = "glowget", url = "https://pomf2.lain.la/f/qljx5ro.png"},
{ name = "machoget", url = "https://pomf2.lain.la/f/ht0b3bx.png"},
{ name = "numschwitz", url = "https://pomf2.lain.la/f/l2dk57t4.png"},
{ name = "pezget", url = "https://pomf2.lain.la/f/9gkkwaln.png"},
{ name = "slowget", url = "https://pomf2.lain.la/f/wt89ccr.png"},
{ name = "strawget", url = "https://pomf2.lain.la/f/ifaekl6.png"},
{ name = "tallget", url = "https://pomf2.lain.la/f/mb8n0dn9.png"},
{ name = "washget", url = "https://pomf2.lain.la/f/v2kimh5.gif"},
{ name = "washgetfast", url = "https://pomf2.lain.la/f/txa0fvde.gif"},
{ name = "gangetbloo", url = "https://pomf2.lain.la/f/qnaz5gwp.png"},
{ name = "gangetcrip", url = "https://pomf2.lain.la/f/fnyczt8g.png"},
{ name = "ganget", url = "https://pomf2.lain.la/f/fy2q2jlq.png"},
{ name = "kot", url = "https://smart.bluefast.horse/kissable-s480l68.png"},
{ name = "wideget", url = "https://kissable.bluefast.horse/z9h0ujq.png"},
{ name = "numrect", url = "https://kissable.bluefast.horse/qt6oco1.gif"},
{ name = "pon3.stream", url = "https://kissable.bluefast.horse/jzdokvmj.png"},
{ name = "poledance", url = "https://smart.bluefast.horse/catbox-cem7gi.gif"},
{ name = "nawni.og", url = "https://pomf2.lain.la/f/z66pfdv8.png"}}

fadeSpeed = 0.0025
offsetSpeed = 0.5
offsetXSpeedDelta = 4
emoteWidth = 50
ids = {}
function uuid()
  local template ='xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
  return string.gsub(template, '[xy]', function (c)
    local v = (c == 'x') and random(0, 0xf) or random(8, 0xb)
    return string.format('%x', v)
  end)
end

function onLoad()
  assets = UI.getCustomAssets()
  assetsSet = {}
  for _, asset in pairs(assets) do
    assetsSet[asset['name']] = true
  end
  for _, emote in pairs(emotesAssets) do
    if assetsSet[emote['name']] == nil then 
      assets[#assets+1] = emote
    end
  end
  UI.setCustomAssets(assets)
end

function onFixedUpdate()
  for idx, item in pairs(ids) do
    if item['opacity'] > 0.1 then
      item['opacity'] = item['opacity'] - fadeSpeed
      UI.setAttribute(item['id'], "color", 'rgba(1,1,1,'..item['opacity']..')')
      if math.random() > 0.98 then
        item['offsetXDelta'] = ((math.random(0, offsetXSpeedDelta*2)-offsetXSpeedDelta)/10)
      end
      numbers = {}
      for num in item['offsetXY']:gmatch("%S+") do
        table.insert(numbers, tonumber(num))
      end
      item['offsetXY'] = numbers[1]+item['offsetXDelta'] .. ' ' .. numbers[2]+offsetSpeed
      UI.setAttribute(item['id'], "offsetXY", item['offsetXY'])
    elseif item['id'] then
      self.UI.hide(item['id'])
      UI.hide(item['id'])
      table.remove(ids, idx)
    end
  end
end

function onChat(message, player)
  for w in message:gmatch("%S+") do 
    if emotes[w] then
      id = uuid()
      ids[#ids+1] = {
        id = id,
        offsetXDelta = ((math.random(0, offsetXSpeedDelta*2)-offsetXSpeedDelta)/10),
        offsetXY = "0 0",
        opacity = 1,
      }
      grid = self.UI.getXmlTable('grid')
      if grid then
        gridEl = grid[1]
        children = gridEl['children']
        children[#children+1] = {
          tag="Image",
          attributes={
            id=id,
            rectAlignment='LowerLeft',
            width=emoteWidth,
            preserveAspect='true',
            image=w,
            color="rgba(1,1,1,1)",
            offsetXY="0 0"
          },
        }
        UI.setXmlTable(grid)
        UI.show("grid")
        self.UI.setXmlTable(grid)
        self.UI.hide("grid")
      end
    end
  end
end